### ISSUE TITLE
technologie verwijderen

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [onderwijsarchitectuur/kernmodel#15]
Vanwege de openbaarheid van github is het onwenselijk om eventuele gevoelige technische keuzes verwoord in architectuur op deze manier te uiten. Kan dat nu niet overzien. @aminne65 @reneberken @harmgeert, . Ik wil alle technische elementen en views verwijderen. Probleem mee?

**Comment by onderwijsarchitectuur** [comment]
De  pull request van  @jwvveen is doorgevoerd via de commandline.
